# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14xcVz1zDGYaJGZnnS9MsaaHy1A5Nl3gj
"""



import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


square_footage = np.array([1000, 1500, 1200, 1700, 900]).reshape(-1, 1)
bedrooms = np.array([2, 3, 2, 4, 1]).reshape(-1, 1)
bathrooms = np.array([1, 2, 1.5, 2.5, 1]).reshape(-1, 1)
prices = np.array([150000, 200000, 180000, 230000, 120000])


features = np.concatenate((square_footage, bedrooms, bathrooms), axis=1)


X_train, X_test, y_train, y_test = train_test_split(features, prices, test_size=0.2, random_state=42)


model = LinearRegression()
model.fit(X_train, y_train)


predictions = model.predict(X_test)

mse = mean_squared_error(y_test, predictions)
print("Mean Squared Error:", mse)

print("Coefficients:", model.coef_)


print("Intercept:", model.intercept_)





